# Generated by Django 4.1.3 on 2023-08-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timecatcherapi', '0004_timelineevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='BCE',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='user_id',
            field=models.ForeignKey(db_column='user_id_id', on_delete=django.db.models.deletion.CASCADE, to='timecatcherapi.user'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='user_id',
            field=models.ForeignKey(db_column='user_id_id', on_delete=django.db.models.deletion.CASCADE, to='timecatcherapi.user'),
        ),
    ]
