# Generated by Django 4.1.3 on 2023-08-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecatcherapi', '0005_event_bce_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
