# Generated by Django 4.1.3 on 2023-09-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timecatcherapi', '0007_alter_event_description_alter_event_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=1000)),
                ('public', models.BooleanField()),
                ('gallery', models.BooleanField()),
                ('date_added', models.IntegerField()),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='timecatcherapi.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='timecatcherapi.user')),
            ],
        ),
    ]
