# Generated by Django 4.1.3 on 2023-09-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timecatcherapi', '0010_followuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('date', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timecatcherapi.event')),
                ('user', models.ForeignKey(db_column='user_id_id', on_delete=django.db.models.deletion.CASCADE, to='timecatcherapi.user')),
            ],
        ),
    ]
