# Generated by Django 4.1.3 on 2023-09-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timecatcherapi', '0012_alter_thread_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timecatcherapi.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timecatcherapi.user')),
            ],
        ),
    ]
