# Generated by Django 4.1.3 on 2023-09-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timecatcherapi', '0013_followthread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowThread',
        ),
    ]
