# Generated by Django 4.1.3 on 2023-09-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecatcherapi', '0016_threadcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='description',
            field=models.CharField(default='No Description', max_length=100000),
        ),
    ]
